version: '3.4'
# https://github.com/nellmedina/jenkins-docker/tree/master/master-slave

services:
  # Jenkins Master
  jenkins:
    image: blacklabelops/jenkins:2.89.3
    container_name: jenkins
    hostname: jenkins
    networks:
      - ci
    ports:
     - "8080:8080"
    volumes:
      - "/srv/jenkins:/srv/jenkins"
    environment:
      - JENKINS_HOME=/srv/jenkins
      # Setting up the admin account and basic security
      - JENKINS_ADMIN_USER=admin
      - JENKINS_ADMIN_PASSWORD=password
      # Specify the Java VM parameters
      # See: http://www.oracle.com/technetwork/articles/java/vmoptions-jsp-140102.html
      - JAVA_VM_PARAMETERS=-Xmx1536m -Xms512m
      # Number of executors on Jenkins master.
      - JENKINS_MASTER_EXECUTORS=0
      # Whitespace separated list of required plugins.
      # Example: gitlab-plugin hipchat swarm
      - JENKINS_PLUGINS=swarm blueocean docker-workflow jenkins-gitlab-hook-plugin gitlab-oauth nexus-jenkins-plugin
      # Parameters for setting up HTTP.
      # Example:
      #JENKINS_KEYSTORE_PASSWORD=swordfish
      #JENKINS_CERTIFICATE_DNAME=CN=SBleul,OU=Blacklabelops,O=blacklabelops.com,L=Munich,S=Bavaria,C=D
      #JENKINS_KEYSTORE_PASSWORD=
      #JENKINS_CERTIFICATE_DNAME="CN=SBleul,OU=Blacklabelops,O=blacklabelops.net,L=Munich,S=Bavaria,C=DE"
      # Jenkins port for accepting swarm slave connections
      - JENKINS_SLAVEPORT=50000
      # Jenkins startup parameters.
      # See: https://wiki.jenkins-ci.org/display/JENKINS/Starting+and+Accessing+Jenkins
      - JENKINS_PARAMETERS=
      # Jenkins Mail Setup
      - SMTP_USER_NAME=
      - SMTP_USER_PASS=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_REPLYTO_ADDRESS=
      - SMTP_USE_SSL=
      - SMTP_CHARSET=
      # Jenkins log file. Not necessary, because Jenkins logs to Docker.
      - JENKINS_LOG_FILE=
    labels:
      com.blacklabelops.description: "Jenkins Continuous Integration System"
      com.blacklabelops.service: "jenkins-master"
    deploy:
      placement:
        constraints:
          - node.hostname==veras
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: start-first
        monitor: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Jenkins Slave
  slave:
    image: blacklabelops/swarm-dockerhost
    networks:
      - ci
    environment:
      # note to secure passwords!
      - SWARM_JENKINS_USER=admin
      - SWARM_JENKINS_PASSWORD=password
      - SWARM_VM_PARAMETERS=-Xmx512m -Xms256m
      - SWARM_CLIENT_EXECUTORS=4
      # SWARM_CLIENT_LABELS=jdk8 java
      # SWARM_CLIENT_PARAMETERS=-name 'Super-Build' -description 'Super Client'
      # SWARM_MASTER_URL=http://localhost:8090/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.blacklabelops.description: "Jenkins Swarm JDK-8 Slave"
      com.blacklabelops.service: "slave"
      com.blacklabelops.applications: "java maven gradle"
    deploy:
      placement:
        constraints:
          - node.role!=manager
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: start-first
        monitor: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  ci:
